/**
 * Wellington Dam Dive Map
 * Interactive map with bathymetry visualization and survey line overlays
 */

// ============================================
// Configuration
// ============================================

// Volume-to-Level Lookup Table (calibrated from bathymetry + survey cross-reference)
// Generated by generate_volume_lookup.py using:
// - Survey cross-reference: 84.35 GL @ 156.96m AHD
// - Full supply reference: 185 GL @ 165.5m AHD
const VOLUME_TO_LEVEL = [
    { volumeGL: 0, levelAHD: 126.0 },
    { volumeGL: 50, levelAHD: 153.8 },
    { volumeGL: 60, levelAHD: 154.7 },
    { volumeGL: 70, levelAHD: 155.7 },
    { volumeGL: 80, levelAHD: 156.6 },
    { volumeGL: 84.35, levelAHD: 156.96 },
    { volumeGL: 90, levelAHD: 157.5 },
    { volumeGL: 100, levelAHD: 158.3 },
    { volumeGL: 120, levelAHD: 159.9 },
    { volumeGL: 150, levelAHD: 162.6 },
    { volumeGL: 185, levelAHD: 165.5 },
];

/**
 * Get water level from storage volume using calibrated lookup table
 * @param {number} volumeGL - Storage volume in gigalitres
 * @returns {number} Water level in meters AHD
 */
function getWaterLevelFromVolume(volumeGL) {
    if (volumeGL <= VOLUME_TO_LEVEL[0].volumeGL) {
        return VOLUME_TO_LEVEL[0].levelAHD;
    }
    if (volumeGL >= VOLUME_TO_LEVEL[VOLUME_TO_LEVEL.length - 1].volumeGL) {
        return VOLUME_TO_LEVEL[VOLUME_TO_LEVEL.length - 1].levelAHD;
    }

    for (let i = 1; i < VOLUME_TO_LEVEL.length; i++) {
        if (volumeGL <= VOLUME_TO_LEVEL[i].volumeGL) {
            const prev = VOLUME_TO_LEVEL[i - 1];
            const curr = VOLUME_TO_LEVEL[i];
            const t = (volumeGL - prev.volumeGL) / (curr.volumeGL - prev.volumeGL);
            return prev.levelAHD + t * (curr.levelAHD - prev.levelAHD);
        }
    }
    return VOLUME_TO_LEVEL[VOLUME_TO_LEVEL.length - 1].levelAHD;
}

const CONFIG = {
    INITIAL_VIEW: {
        lng: 115.9930,
        lat: -33.3900,
        zoom: 15
    },

    // Bathymetry COG files
    BATHY_COG: 'merged_bathy_cog.tif',
    HILLSHADE_COG: 'hillshade_cog.tif',

    // Water level configuration (from calibrated volume model)
    // Update CURRENT_STORAGE_GL to recalculate water level automatically
    CURRENT_STORAGE_GL: 84.35,
    WATER_LEVEL_DATE: '2026-01-26',
    get WATER_LEVEL_AHD() { return getWaterLevelFromVolume(this.CURRENT_STORAGE_GL); },

    // Elevation and depth ranges (dynamically calculated)
    MIN_ELEVATION_AHD: 126.0,
    get MAX_ELEVATION_AHD() { return this.WATER_LEVEL_AHD; },
    get DEPTH_RANGE() { return [0, Math.round(this.WATER_LEVEL_AHD - this.MIN_ELEVATION_AHD)]; },

    // Survey line files and colors
    SURVEY_LINE_FILES: [
        'north_adjusted.csv',
        'south_adjusted.csv',
        'northT1_adjusted.csv',
        'northT2_adjusted.csv',
        'southT1_adjusted.csv'
    ],
    SURVEY_LINE_COLORS: {
        'north_adjusted': '#FF6B6B',
        'south_adjusted': '#4ECDC4',
        'northT1_adjusted': '#FFE66D',
        'northT2_adjusted': '#95E1D3',
        'southT1_adjusted': '#AA96DA'
    },
    SURVEY_LINE_NAMES: {
        'north_adjusted': 'North Line',
        'south_adjusted': 'South Line',
        'northT1_adjusted': 'North Traverse 1',
        'northT2_adjusted': 'North Traverse 2',
        'southT1_adjusted': 'South Traverse 1'
    },

    // Contour configuration
    CONTOUR_COLOR: '#000000',
    CONTOUR_INTERVALS: {
        16: 1    // Zoom 16+: 2m intervals
    },
    // Contours for depth below water surface (negative of AHD minus water level)
    // Generate contours at AHD levels that correspond to 5m, 10m, 15m... depth
    MIN_CONTOUR_DEPTH: 0,
    MAX_CONTOUR_DEPTH: 31
};

// ============================================
// State
// ============================================

const state = {
    layerVisibility: {
        bathymetry: true,
        contours: true
    },
    measureMode: false,
    measurePoints: [],
    totalDistance: 0,
    activePopup: null,
    surveyData: {},      // Survey line GeoJSON data by filename
    contoursCache: new Map(),
    isGeneratingContours: false,
    geoTiffImage: null,  // Bathymetry GeoTIFF reference for contour generation
    hillshadeLayer: null, // Custom WebGL hillshade layer reference

    // Water level control state
    useCurrentLevel: true,           // Whether to use Water Corp current level
    customStorageGL: 84,             // Custom storage level when not using current
};

/**
 * Get the active storage volume in GL (either current or custom)
 */
function getActiveStorageGL() {
    return state.useCurrentLevel ? CONFIG.CURRENT_STORAGE_GL : state.customStorageGL;
}

/**
 * Get the active water level in meters AHD
 */
function getActiveWaterLevel() {
    return getWaterLevelFromVolume(getActiveStorageGL());
}

/**
 * Get the active depth range based on current water level
 */
function getActiveDepthRange() {
    const waterLevel = getActiveWaterLevel();
    return [0, Math.round(waterLevel - CONFIG.MIN_ELEVATION_AHD)];
}

// ============================================
// Utilities
// ============================================

// Turbo colormap (QGIS-compatible)
// Full 256-value Turbo colormap
const TURBO_COLORMAP = [
    [0.18995,0.07176,0.23217],[0.19483,0.08339,0.26149],[0.19956,0.09498,0.29024],[0.20415,0.10652,0.31844],
    [0.20860,0.11802,0.34607],[0.21291,0.12947,0.37314],[0.21708,0.14087,0.39964],[0.22111,0.15223,0.42558],
    [0.22500,0.16354,0.45096],[0.22875,0.17481,0.47578],[0.23236,0.18603,0.50004],[0.23582,0.19720,0.52373],
    [0.23915,0.20833,0.54686],[0.24234,0.21941,0.56942],[0.24539,0.23044,0.59142],[0.24830,0.24143,0.61286],
    [0.25107,0.25237,0.63374],[0.25369,0.26327,0.65406],[0.25618,0.27412,0.67381],[0.25853,0.28492,0.69300],
    [0.26074,0.29568,0.71162],[0.26280,0.30639,0.72968],[0.26473,0.31706,0.74718],[0.26652,0.32768,0.76412],
    [0.26816,0.33825,0.78050],[0.26967,0.34878,0.79631],[0.27103,0.35926,0.81156],[0.27226,0.36970,0.82624],
    [0.27334,0.38008,0.84037],[0.27429,0.39043,0.85393],[0.27509,0.40072,0.86692],[0.27576,0.41097,0.87936],
    [0.27628,0.42118,0.89123],[0.27667,0.43134,0.90254],[0.27691,0.44145,0.91328],[0.27701,0.45152,0.92347],
    [0.27698,0.46153,0.93309],[0.27680,0.47151,0.94214],[0.27648,0.48144,0.95064],[0.27603,0.49132,0.95857],
    [0.27543,0.50115,0.96594],[0.27469,0.51094,0.97275],[0.27381,0.52069,0.97899],[0.27273,0.53040,0.98461],
    [0.27106,0.54015,0.98930],[0.26878,0.54995,0.99303],[0.26592,0.55979,0.99583],[0.26252,0.56967,0.99773],
    [0.25862,0.57958,0.99876],[0.25425,0.58950,0.99896],[0.24946,0.59943,0.99835],[0.24427,0.60937,0.99697],
    [0.23874,0.61931,0.99485],[0.23288,0.62923,0.99202],[0.22676,0.63913,0.98851],[0.22039,0.64901,0.98436],
    [0.21382,0.65886,0.97959],[0.20708,0.66866,0.97423],[0.20021,0.67842,0.96833],[0.19326,0.68812,0.96190],
    [0.18625,0.69775,0.95498],[0.17923,0.70732,0.94761],[0.17223,0.71680,0.93981],[0.16529,0.72620,0.93161],
    [0.15844,0.73551,0.92305],[0.15173,0.74472,0.91416],[0.14519,0.75381,0.90496],[0.13886,0.76279,0.89550],
    [0.13278,0.77165,0.88580],[0.12698,0.78037,0.87590],[0.12151,0.78896,0.86581],[0.11639,0.79740,0.85559],
    [0.11167,0.80569,0.84525],[0.10738,0.81381,0.83484],[0.10357,0.82177,0.82437],[0.10026,0.82955,0.81389],
    [0.09750,0.83714,0.80342],[0.09532,0.84455,0.79299],[0.09377,0.85175,0.78264],[0.09287,0.85875,0.77240],
    [0.09267,0.86554,0.76230],[0.09320,0.87211,0.75237],[0.09451,0.87844,0.74265],[0.09662,0.88454,0.73316],
    [0.09958,0.89040,0.72393],[0.10342,0.89600,0.71500],[0.10815,0.90142,0.70599],[0.11374,0.90673,0.69651],
    [0.12014,0.91193,0.68660],[0.12733,0.91701,0.67627],[0.13526,0.92197,0.66556],[0.14391,0.92680,0.65448],
    [0.15323,0.93151,0.64308],[0.16319,0.93609,0.63137],[0.17377,0.94053,0.61938],[0.18491,0.94484,0.60713],
    [0.19659,0.94901,0.59466],[0.20877,0.95304,0.58199],[0.22142,0.95692,0.56914],[0.23449,0.96065,0.55614],
    [0.24797,0.96423,0.54303],[0.26180,0.96765,0.52981],[0.27597,0.97092,0.51653],[0.29042,0.97403,0.50321],
    [0.30513,0.97697,0.48987],[0.32006,0.97974,0.47654],[0.33517,0.98234,0.46325],[0.35043,0.98477,0.45002],
    [0.36581,0.98702,0.43688],[0.38127,0.98909,0.42386],[0.39678,0.99098,0.41098],[0.41229,0.99268,0.39826],
    [0.42778,0.99419,0.38575],[0.44321,0.99551,0.37345],[0.45854,0.99663,0.36140],[0.47375,0.99755,0.34963],
    [0.48879,0.99828,0.33816],[0.50362,0.99879,0.32701],[0.51822,0.99910,0.31622],[0.53255,0.99919,0.30581],
    [0.54658,0.99907,0.29581],[0.56026,0.99873,0.28623],[0.57357,0.99817,0.27712],[0.58646,0.99739,0.26849],
    [0.59891,0.99638,0.26038],[0.61088,0.99514,0.25280],[0.62233,0.99366,0.24579],[0.63323,0.99195,0.23937],
    [0.64362,0.98999,0.23356],[0.65394,0.98775,0.22835],[0.66428,0.98524,0.22370],[0.67462,0.98246,0.21960],
    [0.68494,0.97941,0.21602],[0.69525,0.97610,0.21294],[0.70553,0.97255,0.21032],[0.71577,0.96875,0.20815],
    [0.72596,0.96470,0.20640],[0.73610,0.96043,0.20504],[0.74617,0.95593,0.20406],[0.75617,0.95121,0.20343],
    [0.76608,0.94627,0.20311],[0.77591,0.94113,0.20310],[0.78563,0.93579,0.20336],[0.79524,0.93025,0.20386],
    [0.80473,0.92452,0.20459],[0.81410,0.91861,0.20552],[0.82333,0.91253,0.20663],[0.83241,0.90627,0.20788],
    [0.84133,0.89986,0.20926],[0.85010,0.89328,0.21074],[0.85868,0.88655,0.21230],[0.86709,0.87968,0.21391],
    [0.87530,0.87267,0.21555],[0.88331,0.86553,0.21719],[0.89112,0.85826,0.21880],[0.89870,0.85087,0.22038],
    [0.90605,0.84337,0.22188],[0.91317,0.83576,0.22328],[0.92004,0.82806,0.22456],[0.92666,0.82025,0.22570],
    [0.93301,0.81236,0.22667],[0.93909,0.80439,0.22744],[0.94489,0.79634,0.22800],[0.95039,0.78823,0.22831],
    [0.95560,0.78005,0.22836],[0.96049,0.77181,0.22811],[0.96507,0.76352,0.22754],[0.96931,0.75519,0.22663],
    [0.97323,0.74682,0.22536],[0.97679,0.73842,0.22369],[0.98000,0.73000,0.22161],[0.98289,0.72140,0.21918],
    [0.98549,0.71250,0.21650],[0.98781,0.70330,0.21358],[0.98986,0.69382,0.21043],[0.99163,0.68408,0.20706],
    [0.99314,0.67408,0.20348],[0.99438,0.66386,0.19971],[0.99535,0.65341,0.19577],[0.99607,0.64277,0.19165],
    [0.99654,0.63193,0.18738],[0.99675,0.62093,0.18297],[0.99672,0.60977,0.17842],[0.99644,0.59846,0.17376],
    [0.99593,0.58703,0.16899],[0.99517,0.57549,0.16412],[0.99419,0.56386,0.15918],[0.99297,0.55214,0.15417],
    [0.99153,0.54036,0.14910],[0.98987,0.52854,0.14398],[0.98799,0.51667,0.13883],[0.98590,0.50479,0.13367],
    [0.98360,0.49291,0.12849],[0.98108,0.48104,0.12332],[0.97837,0.46920,0.11817],[0.97545,0.45740,0.11305],
    [0.97234,0.44565,0.10797],[0.96904,0.43399,0.10294],[0.96555,0.42241,0.09798],[0.96187,0.41093,0.09310],
    [0.95801,0.39958,0.08831],[0.95398,0.38836,0.08362],[0.94977,0.37729,0.07905],[0.94538,0.36638,0.07461],
    [0.94084,0.35566,0.07031],[0.93612,0.34513,0.06616],[0.93125,0.33482,0.06218],[0.92623,0.32473,0.05837],
    [0.92105,0.31489,0.05475],[0.91572,0.30530,0.05134],[0.91024,0.29599,0.04814],[0.90463,0.28696,0.04516],
    [0.89888,0.27824,0.04243],[0.89298,0.26981,0.03993],[0.88691,0.26152,0.03753],[0.88066,0.25334,0.03521],
    [0.87422,0.24526,0.03297],[0.86760,0.23730,0.03082],[0.86079,0.22945,0.02875],[0.85380,0.22170,0.02677],
    [0.84662,0.21407,0.02487],[0.83926,0.20654,0.02305],[0.83172,0.19912,0.02131],[0.82399,0.19182,0.01966],
    [0.81608,0.18462,0.01809],[0.80799,0.17753,0.01660],[0.79971,0.17055,0.01520],[0.79125,0.16368,0.01387],
    [0.78260,0.15693,0.01264],[0.77377,0.15028,0.01148],[0.76476,0.14374,0.01041],[0.75556,0.13731,0.00942],
    [0.74617,0.13098,0.00851],[0.73661,0.12477,0.00769],[0.72686,0.11867,0.00695],[0.71692,0.11268,0.00629],
    [0.70680,0.10680,0.00571],[0.69650,0.10102,0.00522],[0.68602,0.09536,0.00481],[0.67535,0.08980,0.00449],
    [0.66449,0.08436,0.00424],[0.65345,0.07902,0.00408],[0.64223,0.07380,0.00401],[0.63082,0.06868,0.00401],
    [0.61923,0.06367,0.00410],[0.60746,0.05878,0.00427],[0.59550,0.05399,0.00453],[0.58336,0.04931,0.00486],
    [0.57103,0.04474,0.00529],[0.55852,0.04028,0.00579],[0.54583,0.03593,0.00638],[0.53295,0.03169,0.00705],
    [0.51989,0.02756,0.00780],[0.50664,0.02354,0.00863],[0.49321,0.01963,0.00955],[0.47960,0.01583,0.01055]
];

/**
 * Map depth value to RGB color using Turbo colormap
 * Shallow (0m) = blue end, Deep (30m) = red end
 */
function getTurboColorForDepth(depth, minDepth = 0, maxDepth = 31) {
    // Normalize depth to 0-1 range
    const normalized = (depth - minDepth) / (maxDepth - minDepth);
    const clamped = Math.max(0, Math.min(1, normalized));

    // Invert so shallow (0) = red, deep = blue/purple
    const inverted = 1 - clamped;

    // Map to colormap index
    const index = inverted * (TURBO_COLORMAP.length - 1);
    const lower = Math.floor(index);
    const upper = Math.ceil(index);
    const fraction = index - lower;

    // Interpolate between colors
    const colorLower = TURBO_COLORMAP[lower];
    const colorUpper = TURBO_COLORMAP[upper];

    return [
        Math.round((colorLower[0] + (colorUpper[0] - colorLower[0]) * fraction) * 255),
        Math.round((colorLower[1] + (colorUpper[1] - colorLower[1]) * fraction) * 255),
        Math.round((colorLower[2] + (colorUpper[2] - colorLower[2]) * fraction) * 255)
    ];
}

/**
 * Convert bed elevation (AHD) to depth below water surface
 */
function elevationToDepth(elevationAHD) {
    return getActiveWaterLevel() - elevationAHD;
}

/**
 * Calculate distance between two points using Haversine formula
 */
function haversineDistance([lon1, lat1], [lon2, lat2]) {
    const R = 6371000; // Earth radius in meters
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;
    const a = Math.sin(dLat / 2) ** 2 +
        Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
        Math.sin(dLon / 2) ** 2;
    return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

/**
 * Format distance for display
 */
function formatDistance(meters) {
    if (meters >= 1000) {
        return `${(meters / 1000).toFixed(2)} km`;
    }
    return `${meters.toFixed(1)} m`;
}

/**
 * Format coordinates in multiple formats
 */
function formatCoordinates(lng, lat) {
    const gmaps = `${lat.toFixed(6)}, ${lng.toFixed(6)}`;
    const latDeg = Math.floor(Math.abs(lat));
    const latMin = ((Math.abs(lat) % 1) * 60).toFixed(3);
    const latDir = lat >= 0 ? 'N' : 'S';
    const lngDeg = Math.floor(Math.abs(lng));
    const lngMin = ((Math.abs(lng) % 1) * 60).toFixed(3);
    const lngDir = lng >= 0 ? 'E' : 'W';
    const dm = `${latDeg}° ${latMin}' ${latDir}, ${lngDeg}° ${lngMin}' ${lngDir}`;
    return { gmaps, display: dm };
}

/**
 * Debounce helper function
 */
function debounce(func, wait) {
    let timeout;
    return function executedFunction(...args) {
        const later = () => {
            clearTimeout(timeout);
            func(...args);
        };
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
    };
}

// ============================================
// Map Initialization
// ============================================

// Register COG protocol for bathymetry raster
maplibregl.addProtocol('cog', MaplibreCOGProtocol.cogProtocol);

const map = new maplibregl.Map({
    container: 'map',
    style: {
        version: 8,
        glyphs: 'https://demotiles.maplibre.org/font/{fontstack}/{range}.pbf',
        sources: {
            'esri-satellite': {
                type: 'raster',
                tiles: [
                    'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'
                ],
                tileSize: 256,
                maxzoom: 18
            }
        },
        layers: [
            {
                id: 'satellite-layer',
                type: 'raster',
                source: 'esri-satellite',
                minzoom: 0
            }
        ]
    },
    center: [CONFIG.INITIAL_VIEW.lng, CONFIG.INITIAL_VIEW.lat],
    zoom: CONFIG.INITIAL_VIEW.zoom,
    minZoom: 12,
    maxZoom: 20,
    maxPitch: 0,
    dragRotate: false,
    attributionControl: false
});

// Add attribution control (compact)
map.addControl(new maplibregl.AttributionControl({ compact: true }), 'bottom-right');

// Add navigation control
map.addControl(new maplibregl.NavigationControl({ showCompass: false }), 'bottom-right');

// ============================================
// Depth Gradient Legend
// ============================================

function initializeDepthGradient() {
    const gradientEl = document.getElementById('depth-gradient');
    if (!gradientEl) return;

    const [minDepth, maxDepth] = getActiveDepthRange();

    // Generate CSS gradient from Turbo colormap
    const stops = [];
    for (let i = 0; i <= 10; i++) {
        const depth = (i / 10) * maxDepth;
        const [r, g, b] = getTurboColorForDepth(depth, minDepth, maxDepth);
        stops.push(`rgb(${r}, ${g}, ${b}) ${i * 10}%`);
    }

    gradientEl.style.background = `linear-gradient(to bottom, ${stops.join(', ')})`;
}

// ============================================
// Bathymetry Layers
// ============================================

/**
 * Set up color function for bathymetry layer
 * Uses dynamic water level from state
 */
function setupBathymetryColorFunction() {
    MaplibreCOGProtocol.setColorFunction(CONFIG.BATHY_COG, (pixel, color, metadata) => {
        const elevation = pixel[0];
        const waterLevel = getActiveWaterLevel();
        const [minDepth, maxDepth] = getActiveDepthRange();

        // Handle NoData values
        if (elevation === metadata.noData || elevation >= 1e5 || !Number.isFinite(elevation)) {
            color.set([0, 0, 0, 0]);
            return;
        }

        // Don't render areas above water level (not submerged)
        if (elevation > waterLevel) {
            color.set([0, 0, 0, 0]);
            return;
        }

        // Calculate depth and get color
        const depth = waterLevel - elevation;
        const [r, g, b] = getTurboColorForDepth(depth, minDepth, maxDepth);
        color.set([r, g, b, 255]);
    });
}

async function addBathymetryLayers() {
    // Set up color function (will read water level dynamically)
    setupBathymetryColorFunction();

    try {
        // Add bathymetry source and layer
        map.addSource('bathymetry-source', {
            type: 'raster',
            url: `cog://${CONFIG.BATHY_COG}`,
            tileSize: 256
        });

        map.addLayer({
            id: 'bathymetry-layer',
            type: 'raster',
            source: 'bathymetry-source',
            paint: {
                'raster-opacity': 1.0,
                'raster-resampling': 'nearest'
            },
            layout: {
                visibility: state.layerVisibility.bathymetry ? 'visible' : 'none'
            }
        });

        // Add custom WebGL hillshade layer with multiply blend mode
        // This renders on top of bathymetry and darkens shadowed areas
        state.hillshadeLayer = createMultiplyHillshadeLayer({
            id: 'hillshade-layer',
            cogUrl: CONFIG.HILLSHADE_COG,
            opacity: 1.0
        });

        map.addLayer(state.hillshadeLayer);

        console.log('Bathymetry layers added successfully');
    } catch (error) {
        console.error('Failed to add bathymetry layers:', error);
    }
}

// ============================================
// Survey Line Loading
// ============================================

async function loadSurveyLines() {
    const allFeatures = [];

    for (const filename of CONFIG.SURVEY_LINE_FILES) {
        try {
            const response = await fetch(filename);
            if (!response.ok) {
                console.warn(`Could not load ${filename}`);
                continue;
            }

            const csvText = await response.text();
            const lines = csvText.trim().split('\n');
            const headers = lines[0].split(',');

            // Find column indices
            const yIndex = headers.findIndex(h => h.trim() === 'Y');
            const xIndex = headers.findIndex(h => h.trim() === 'X');
            const elevIndex = headers.findIndex(h => h.trim() === 'Elevation');
            const markerIndex = headers.findIndex(h => h.trim() === 'Marker');

            if (yIndex === -1 || xIndex === -1) {
                console.warn(`Missing Y/X columns in ${filename}`);
                continue;
            }

            // Parse coordinates and create line
            const coordinates = [];
            const points = [];

            for (let i = 1; i < lines.length; i++) {
                const values = lines[i].split(',');
                const lat = parseFloat(values[yIndex]);
                const lng = parseFloat(values[xIndex]);
                const elevation = elevIndex !== -1 ? parseFloat(values[elevIndex]) : null;
                const marker = markerIndex !== -1 ? values[markerIndex]?.trim() : null;

                if (!isNaN(lat) && !isNaN(lng)) {
                    coordinates.push([lng, lat]);
                    points.push({
                        coord: [lng, lat],
                        elevation: elevation,  // Depth below surface (negative)
                        marker: marker
                    });
                }
            }

            if (coordinates.length >= 2) {
                // Store the survey data
                const lineKey = filename.replace('.csv', '');
                state.surveyData[lineKey] = {
                    coordinates,
                    points,
                    color: CONFIG.SURVEY_LINE_COLORS[lineKey],
                    name: CONFIG.SURVEY_LINE_NAMES[lineKey]
                };

                // Create LineString feature
                allFeatures.push({
                    type: 'Feature',
                    geometry: {
                        type: 'LineString',
                        coordinates: coordinates
                    },
                    properties: {
                        lineKey: lineKey,
                        name: CONFIG.SURVEY_LINE_NAMES[lineKey],
                        color: CONFIG.SURVEY_LINE_COLORS[lineKey],
                        pointCount: coordinates.length
                    }
                });

                console.log(`Loaded ${filename}: ${coordinates.length} points`);
            }
        } catch (error) {
            console.error(`Error loading ${filename}:`, error);
        }
    }

    // Add survey lines to map
    if (allFeatures.length > 0) {
        map.addSource('survey-lines', {
            type: 'geojson',
            data: {
                type: 'FeatureCollection',
                features: allFeatures
            }
        });

        // Build color expression
        const colorExpression = ['match', ['get', 'lineKey']];
        Object.entries(CONFIG.SURVEY_LINE_COLORS).forEach(([key, color]) => {
            colorExpression.push(key, color);
        });
        colorExpression.push('#888888');

        // Add visible line layer
        map.addLayer({
            id: 'survey-lines-layer',
            type: 'line',
            source: 'survey-lines',
            paint: {
                'line-color': colorExpression,
                'line-width': 4,
                'line-opacity': 0.9
            }
        });

        // Add hit area for easier clicking
        map.addLayer({
            id: 'survey-lines-hitarea',
            type: 'line',
            source: 'survey-lines',
            paint: {
                'line-color': '#000000',
                'line-width': 20,
                'line-opacity': 0
            }
        });
    }
}

// ============================================
// Contour Generation
// ============================================

async function initializeContourGeneration() {
    try {
        const tiff = await GeoTIFF.fromUrl(CONFIG.BATHY_COG, {
            allowFullFile: false,
            cacheSize: 100
        });

        state.geoTiffImage = await tiff.getImage();

        // Add empty contours source
        map.addSource('contours-source', {
            type: 'geojson',
            data: { type: 'FeatureCollection', features: [] }
        });

        // Add contour line layer
        map.addLayer({
            id: 'contours-layer',
            type: 'line',
            source: 'contours-source',
            paint: {
                'line-color': CONFIG.CONTOUR_COLOR,
                'line-width': [
                    'case',
                    ['==', ['%', ['get', 'depth'], 10], 0],
                    2,
                    1
                ],
                'line-opacity': 0.6
            },
            layout: {
                visibility: state.layerVisibility.contours ? 'visible' : 'none'
            },
            minzoom: Math.min(...Object.keys(CONFIG.CONTOUR_INTERVALS).map(Number))
        }, 'survey-lines-layer');

        // Add contour labels
        map.addLayer({
            id: 'contours-labels',
            type: 'symbol',
            source: 'contours-source',
            paint: {
                'text-color': CONFIG.CONTOUR_COLOR,
                'text-halo-color': '#ffffff',
                'text-halo-width': 2,
                'text-opacity': 0.9
            },
            layout: {
                'text-field': ['concat', ['get', 'depth'], 'm'],
                'text-font': ['Open Sans Regular', 'Arial Unicode MS Regular'],
                'text-size': 11,
                'symbol-placement': 'line',
                'symbol-spacing': 200,
                'text-rotation-alignment': 'map',
                'text-pitch-alignment': 'viewport',
                'text-max-angle': 30,
                'text-padding': 10,
                visibility: state.layerVisibility.contours ? 'visible' : 'none'
            },
            minzoom: Math.min(...Object.keys(CONFIG.CONTOUR_INTERVALS).map(Number))
        }, 'survey-lines-layer');

        // Generate initial contours
        if (map.getZoom() >= Math.min(...Object.keys(CONFIG.CONTOUR_INTERVALS).map(Number))) {
            await generateContoursForViewport();
        }

        // Regenerate on map movement
        map.on('moveend', debounce(generateContoursForViewport, 300));

    } catch (error) {
        console.error('Failed to initialize contour generation:', error);
    }
}

async function generateContoursForViewport() {
    if (state.isGeneratingContours || !state.geoTiffImage) return;
    if (!state.layerVisibility.contours) return;

    const zoom = Math.floor(map.getZoom());
    const minContourZoom = Math.min(...Object.keys(CONFIG.CONTOUR_INTERVALS).map(Number));
    if (zoom < minContourZoom) return;

    const bounds = map.getBounds();

    // Determine contour interval
    let interval = 10;
    for (const [zoomThreshold, int] of Object.entries(CONFIG.CONTOUR_INTERVALS).sort((a, b) => b[0] - a[0])) {
        if (zoom >= parseInt(zoomThreshold)) {
            interval = int;
            break;
        }
    }

    // Check cache
    const cacheKey = `${zoom}-${interval}-${bounds.toString()}`;
    if (state.contoursCache.has(cacheKey)) {
        map.getSource('contours-source').setData(state.contoursCache.get(cacheKey));
        return;
    }

    state.isGeneratingContours = true;
    document.getElementById('contours-loading')?.classList.add('active');

    try {
        const imageBbox = state.geoTiffImage.getBoundingBox();
        const imageWidth = state.geoTiffImage.getWidth();
        const imageHeight = state.geoTiffImage.getHeight();

        // WGS84 to Web Mercator
        const lngLatToWebMercator = (lng, lat) => {
            const x = (lng * 20037508.34) / 180;
            let y = Math.log(Math.tan(((90 + lat) * Math.PI) / 360)) / (Math.PI / 180);
            y = (y * 20037508.34) / 180;
            return [x, y];
        };

        const [minX, minY] = lngLatToWebMercator(bounds.getWest(), bounds.getSouth());
        const [maxX, maxY] = lngLatToWebMercator(bounds.getEast(), bounds.getNorth());

        const bufferX = (maxX - minX) * 0.5;
        const bufferY = (maxY - minY) * 0.5;

        // Calculate pixel window
        const left = Math.floor(((minX - bufferX - imageBbox[0]) / (imageBbox[2] - imageBbox[0])) * imageWidth);
        const right = Math.ceil(((maxX + bufferX - imageBbox[0]) / (imageBbox[2] - imageBbox[0])) * imageWidth);
        const top = Math.floor(((imageBbox[3] - (maxY + bufferY)) / (imageBbox[3] - imageBbox[1])) * imageHeight);
        const bottom = Math.ceil(((imageBbox[3] - (minY - bufferY)) / (imageBbox[3] - imageBbox[1])) * imageHeight);

        const windowLeft = Math.max(0, left);
        const windowTop = Math.max(0, top);
        const windowRight = Math.min(imageWidth, right);
        const windowBottom = Math.min(imageHeight, bottom);
        const windowWidth = windowRight - windowLeft;
        const windowHeight = windowBottom - windowTop;

        // Determine resolution
        const isMobile = globalThis.innerWidth <= 768;
        const baseResolution = isMobile ? 256 : 512;
        const targetPixels = Math.min(
            baseResolution * Math.pow(2, Math.max(0, zoom - 15)),
            isMobile ? 1024 : 2048
        );

        const aspectRatio = windowWidth / windowHeight;
        let width, height;
        if (aspectRatio > 1) {
            width = targetPixels;
            height = Math.floor(targetPixels / aspectRatio);
        } else {
            height = targetPixels;
            width = Math.floor(targetPixels * aspectRatio);
        }

        // Read elevation data
        const data = await state.geoTiffImage.readRasters({
            window: [windowLeft, windowTop, windowRight, windowBottom],
            width,
            height,
            fillValue: -9999,
            resampleMethod: 'linear'
        });

        const elevationGrid = data[0];

        // Calculate actual extent in Web Mercator
        const actualMinX = imageBbox[0] + (windowLeft / imageWidth) * (imageBbox[2] - imageBbox[0]);
        const actualMaxX = imageBbox[0] + (windowRight / imageWidth) * (imageBbox[2] - imageBbox[0]);
        const actualMaxY = imageBbox[3] - (windowTop / imageHeight) * (imageBbox[3] - imageBbox[1]);
        const actualMinY = imageBbox[3] - (windowBottom / imageHeight) * (imageBbox[3] - imageBbox[1]);

        // Generate depth contour thresholds (converted to AHD elevations)
        // Contours at depths: 5m, 10m, 15m, 20m, 25m, 30m
        // AHD = water_level - depth
        const waterLevel = getActiveWaterLevel();
        const maxContourDepth = Math.round(waterLevel - CONFIG.MIN_ELEVATION_AHD);
        const thresholds = [];
        for (let depth = interval; depth <= maxContourDepth; depth += interval) {
            const ahdLevel = waterLevel - depth;
            if (ahdLevel >= CONFIG.MIN_ELEVATION_AHD) {
                thresholds.push(ahdLevel);
            }
        }

        // Generate contours
        const contourGenerator = d3.contours()
            .size([width, height])
            .thresholds(thresholds)
            .smooth(true);

        const contourMultiPolygons = contourGenerator(elevationGrid);

        // Web Mercator to WGS84
        const webMercatorToLngLat = (x, y) => {
            const lng = (x / 20037508.34) * 180;
            let lat = (y / 20037508.34) * 180;
            lat = (180 / Math.PI) * (2 * Math.atan(Math.exp((lat * Math.PI) / 180)) - Math.PI / 2);
            return [lng, lat];
        };

        // Convert to GeoJSON features
        const features = [];
        const viewportMinX = lngLatToWebMercator(bounds.getWest(), bounds.getSouth())[0];
        const viewportMaxX = lngLatToWebMercator(bounds.getEast(), bounds.getNorth())[0];
        const viewportMinY = lngLatToWebMercator(bounds.getWest(), bounds.getSouth())[1];
        const viewportMaxY = lngLatToWebMercator(bounds.getEast(), bounds.getNorth())[1];

        for (const multiPolygon of contourMultiPolygons) {
            if (multiPolygon.coordinates.length === 0) continue;

            const ahdLevel = multiPolygon.value;
            const depth = Math.round(waterLevel - ahdLevel);

            // Skip invalid depths
            if (depth <= 0) continue;

            for (const polygon of multiPolygon.coordinates) {
                for (const ring of polygon) {
                    // Skip very small rings (noise)
                    if (ring.length < 10) continue;

                    // Transform to geographic coordinates
                    const geoCoords = ring.map(([x, y]) => {
                        const mercatorX = actualMinX + (x / width) * (actualMaxX - actualMinX);
                        const mercatorY = actualMaxY - (y / height) * (actualMaxY - actualMinY);
                        return webMercatorToLngLat(mercatorX, mercatorY);
                    });

                    // Filter contours entirely outside viewport
                    const margin = (viewportMaxX - viewportMinX) * 0.01;
                    let hasInteriorPoint = false;

                    for (const [lng, lat] of geoCoords) {
                        const [mx, my] = lngLatToWebMercator(lng, lat);
                        if (mx > viewportMinX + margin && mx < viewportMaxX - margin &&
                            my > viewportMinY + margin && my < viewportMaxY - margin) {
                            hasInteriorPoint = true;
                            break;
                        }
                    }

                    if (!hasInteriorPoint) continue;

                    features.push({
                        type: 'Feature',
                        properties: {
                            depth: depth,
                            ahdLevel: ahdLevel,
                            interval
                        },
                        geometry: {
                            type: 'LineString',
                            coordinates: geoCoords
                        }
                    });
                }
            }
        }

        const geojson = {
            type: 'FeatureCollection',
            features
        };

        if (map.getSource('contours-source')) {
            map.getSource('contours-source').setData(geojson);
        }

        // Cache
        if (state.contoursCache.size > 20) {
            const firstKey = state.contoursCache.keys().next().value;
            state.contoursCache.delete(firstKey);
        }
        state.contoursCache.set(cacheKey, geojson);

    } catch (error) {
        console.error('Failed to generate contours:', error);
    } finally {
        state.isGeneratingContours = false;
        document.getElementById('contours-loading')?.classList.remove('active');
    }
}

// ============================================
// Measure Tool
// ============================================

function initializeMeasureTool() {
    const measureBtn = document.getElementById('measure-btn');
    const clearBtn = document.getElementById('clear-btn');

    measureBtn.addEventListener('click', (e) => {
        e.stopPropagation();
        state.measureMode = !state.measureMode;
        measureBtn.classList.toggle('active', state.measureMode);

        if (state.measureMode) {
            document.body.classList.add('measure-mode-active');
            clearBtn.style.display = 'block';
        } else {
            document.body.classList.remove('measure-mode-active');
        }

        measureBtn.blur();
    });

    clearBtn.addEventListener('click', (e) => {
        e.stopPropagation();
        clearMeasurements();
    });

    // Add measure sources
    map.addSource('measure-line', {
        type: 'geojson',
        data: { type: 'FeatureCollection', features: [] }
    });

    map.addSource('measure-points', {
        type: 'geojson',
        data: { type: 'FeatureCollection', features: [] }
    });

    map.addLayer({
        id: 'measure-line-layer',
        type: 'line',
        source: 'measure-line',
        paint: {
            'line-color': '#0891b2',
            'line-width': 3,
            'line-dasharray': [2, 2]
        }
    });

    map.addLayer({
        id: 'measure-points-layer',
        type: 'circle',
        source: 'measure-points',
        paint: {
            'circle-radius': 6,
            'circle-color': '#0891b2',
            'circle-stroke-color': '#ffffff',
            'circle-stroke-width': 2
        }
    });
}

function clearMeasurements() {
    state.measurePoints = [];
    state.totalDistance = 0;

    document.getElementById('measure-panel').style.display = 'none';
    document.getElementById('measure-total').textContent = '0 m';
    document.getElementById('measure-items').innerHTML = '';

    map.getSource('measure-line').setData({ type: 'FeatureCollection', features: [] });
    map.getSource('measure-points').setData({ type: 'FeatureCollection', features: [] });
}

async function addMeasurePoint(lngLat) {
    const measurePanel = document.getElementById('measure-panel');
    const measureTotal = document.getElementById('measure-total');
    const measureItems = document.getElementById('measure-items');

    let distance = 0;
    let displayName = 'Start point';

    if (state.measurePoints.length > 0) {
        const lastPoint = state.measurePoints[state.measurePoints.length - 1];
        distance = haversineDistance(
            [lastPoint.lng, lastPoint.lat],
            [lngLat.lng, lngLat.lat]
        );
        displayName = `Point ${state.measurePoints.length + 1}`;
    }

    state.measurePoints.push({
        lng: lngLat.lng,
        lat: lngLat.lat,
        distance: distance
    });

    state.totalDistance += distance;

    measurePanel.style.display = 'block';
    measureTotal.textContent = formatDistance(state.totalDistance);

    const itemEl = document.createElement('div');
    itemEl.className = 'measure-item';
    itemEl.innerHTML = `
        <span class="measure-item-name">
            <span class="measure-item-dot" style="background: #0891b2;"></span>
            ${displayName}
        </span>
        <span class="measure-item-info">
            <span class="measure-item-distance">${formatDistance(distance)}</span>
        </span>
    `;
    measureItems.appendChild(itemEl);

    updateMeasureVisualization();
}

function updateMeasureVisualization() {
    const pointFeatures = state.measurePoints.map((point, index) => ({
        type: 'Feature',
        geometry: {
            type: 'Point',
            coordinates: [point.lng, point.lat]
        },
        properties: { index }
    }));

    map.getSource('measure-points').setData({
        type: 'FeatureCollection',
        features: pointFeatures
    });

    if (state.measurePoints.length >= 2) {
        const lineCoords = state.measurePoints.map(p => [p.lng, p.lat]);
        map.getSource('measure-line').setData({
            type: 'FeatureCollection',
            features: [{
                type: 'Feature',
                geometry: {
                    type: 'LineString',
                    coordinates: lineCoords
                },
                properties: {}
            }]
        });
    }
}

// ============================================
// Click Handlers
// ============================================

function initializeClickHandlers() {
    // Survey line click handler
    map.on('click', 'survey-lines-hitarea', (e) => {
        if (e.features.length === 0) return;

        const feature = e.features[0];
        const props = feature.properties;

        if (state.measureMode) {
            addMeasurePoint(e.lngLat);
        } else {
            const content = `
                <div class="segment-popup">
                    <div class="popup-title">${props.name}</div>
                    <div class="popup-row">
                        <span class="popup-label">Points</span>
                        ${props.pointCount}
                    </div>
                </div>
            `;

            if (state.activePopup) state.activePopup.remove();
            state.activePopup = new maplibregl.Popup({ closeButton: true, maxWidth: '280px' })
                .setLngLat(e.lngLat)
                .setHTML(content)
                .addTo(map);
        }
    });

    // General map click
    map.on('click', (e) => {
        if (!state.measureMode) return;

        const features = map.queryRenderedFeatures(e.point, {
            layers: ['survey-lines-hitarea']
        });

        if (features.length === 0) {
            addMeasurePoint(e.lngLat);
        }
    });

    // Cursor changes
    map.on('mouseenter', 'survey-lines-hitarea', () => {
        if (!state.measureMode) {
            map.getCanvas().style.cursor = 'pointer';
        }
    });

    map.on('mouseleave', 'survey-lines-hitarea', () => {
        if (!state.measureMode) {
            map.getCanvas().style.cursor = '';
        }
    });
}

// ============================================
// Layer Controls
// ============================================

function initializeLayerControls() {
    const layerControls = document.querySelectorAll('.layer-control[data-layer]');

    layerControls.forEach(control => {
        const layerId = control.dataset.layer;
        const checkbox = control.querySelector('input[type="checkbox"]');

        checkbox.addEventListener('change', () => {
            state.layerVisibility[layerId] = checkbox.checked;
            const visibility = checkbox.checked ? 'visible' : 'none';

            if (layerId === 'bathymetry') {
                if (map.getLayer('bathymetry-layer')) {
                    map.setLayoutProperty('bathymetry-layer', 'visibility', visibility);
                }
                // Custom hillshade layer - use opacity for visibility control
                if (state.hillshadeLayer) {
                    state.hillshadeLayer.setOpacity(checkbox.checked ? 1.0 : 0.0);
                    map.triggerRepaint();
                }
            } else if (layerId === 'contours') {
                if (map.getLayer('contours-layer')) {
                    map.setLayoutProperty('contours-layer', 'visibility', visibility);
                }
                if (map.getLayer('contours-labels')) {
                    map.setLayoutProperty('contours-labels', 'visibility', visibility);
                }
                if (checkbox.checked) {
                    generateContoursForViewport();
                }
            }
        });
    });
}

// ============================================
// Mobile Toggle
// ============================================

function initializeMobileToggle() {
    const titleCard = document.querySelector('.title-card');
    const legend = document.querySelector('.legend');
    const legendToggle = document.getElementById('legend-toggle');

    titleCard.addEventListener('click', (e) => {
        if (globalThis.innerWidth <= 768) {
            if (e.target.tagName !== 'A') {
                titleCard.classList.toggle('expanded');
            }
        }
    });

    if (legendToggle && legend) {
        legendToggle.addEventListener('click', (e) => {
            e.stopPropagation();
            e.preventDefault();
            legend.classList.toggle('collapsed');

            const isCollapsed = legend.classList.contains('collapsed');
            localStorage.setItem('legendCollapsed', isCollapsed ? 'true' : 'false');
        });

        if (globalThis.innerWidth <= 768) {
            const savedState = localStorage.getItem('legendCollapsed');
            if (savedState === 'true') {
                legend.classList.add('collapsed');
            }
        }
    }
}

// ============================================
// Legend Zoom to Survey Line
// ============================================

function initializeLegendToggles() {
    const colorItems = document.querySelectorAll('.color-item[data-line]');

    colorItems.forEach(item => {
        item.addEventListener('click', () => {
            const lineKey = item.dataset.line;
            const surveyLine = state.surveyData[lineKey];

            if (surveyLine && surveyLine.coordinates.length > 0) {
                const lngs = surveyLine.coordinates.map(c => c[0]);
                const lats = surveyLine.coordinates.map(c => c[1]);

                const bounds = [
                    [Math.min(...lngs), Math.min(...lats)],
                    [Math.max(...lngs), Math.max(...lats)]
                ];

                const isMobile = globalThis.innerWidth <= 768;
                const padding = isMobile
                    ? { top: 120, bottom: 250, left: 50, right: 50 }
                    : { top: 100, bottom: 100, left: 400, right: 100 };

                map.fitBounds(bounds, {
                    padding: padding,
                    maxZoom: 17,
                    duration: 1000
                });

                colorItems.forEach(ci => ci.classList.remove('selected'));
                item.classList.add('selected');
            }
        });
    });
}

// ============================================
// Context Menu
// ============================================

map.on('contextmenu', (e) => {
    const existing = document.getElementById('context-menu');
    if (existing) existing.remove();

    const { lng, lat } = e.lngLat;
    const coords = formatCoordinates(lng, lat);

    const menu = document.createElement('div');
    menu.id = 'context-menu';
    menu.className = 'context-menu';
    menu.style.left = `${e.point.x}px`;
    menu.style.top = `${e.point.y}px`;

    menu.innerHTML = `
        <div class="context-menu-item" id="copy-dd">
            <span>Copy Decimal Degrees</span>
            <span style="opacity: 0.5; margin-left: 12px; font-size: 0.7rem;">${coords.gmaps}</span>
        </div>
        <div class="context-menu-separator"></div>
        <div class="context-menu-item" id="copy-dm">
            <span>Copy Decimal Minutes</span>
            <span style="opacity: 0.5; margin-left: 12px; font-size: 0.7rem;">${coords.display}</span>
        </div>
        <div class="context-menu-separator"></div>
        <div class="context-menu-item" id="copy-link">
            <span>Copy Link</span>
        </div>
    `;

    document.body.appendChild(menu);

    document.getElementById('copy-dd').addEventListener('click', () => {
        navigator.clipboard.writeText(coords.gmaps);
        menu.remove();
    });

    document.getElementById('copy-dm').addEventListener('click', () => {
        navigator.clipboard.writeText(coords.display);
        menu.remove();
    });

    document.getElementById('copy-link').addEventListener('click', () => {
        const url = `${globalThis.location.origin}${globalThis.location.pathname}#${lat.toFixed(6)},${lng.toFixed(6)}`;
        navigator.clipboard.writeText(url);
        menu.remove();
    });

    const closeMenu = () => {
        menu.remove();
        document.removeEventListener('click', closeMenu);
    };
    setTimeout(() => document.addEventListener('click', closeMenu), 100);
});

// ============================================
// Water Level Display
// ============================================

function updateWaterLevelDisplay() {
    const storageGL = getActiveStorageGL();
    const waterLevel = getActiveWaterLevel();
    const [, maxDepth] = getActiveDepthRange();

    // Update water level note
    const noteEl = document.getElementById('water-level-note');
    if (noteEl) {
        if (state.useCurrentLevel) {
            noteEl.textContent = `Water level: ~${waterLevel.toFixed(1)}m AHD (${storageGL} GL)`;
            noteEl.title = `Current level from Water Corporation (${CONFIG.WATER_LEVEL_DATE})`;
        } else {
            noteEl.textContent = `Water level: ~${waterLevel.toFixed(1)}m AHD (${storageGL} GL)`;
            noteEl.title = 'Custom water level (drag slider to adjust)';
        }
    }

    // Update depth labels based on current range
    const depthLabelsEl = document.querySelector('.depth-labels');
    if (depthLabelsEl) {
        const midDepth = Math.round(maxDepth / 2);
        depthLabelsEl.innerHTML = `<span>0m</span><span>${midDepth}m</span><span>${maxDepth}m</span>`;
    }

    // Update slider value display
    const sliderValueEl = document.getElementById('water-level-value');
    if (sliderValueEl) {
        sliderValueEl.textContent = `${Math.round(storageGL)} GL`;
    }

    // Update depth gradient
    initializeDepthGradient();
}

/**
 * Refresh bathymetry tiles after water level change
 */
function refreshBathymetryTiles() {
    // Force reload by removing and re-adding the source
    // This is needed because the COG protocol caches colored tiles
    const source = map.getSource('bathymetry-source');
    if (source) {
        const visibility = map.getLayoutProperty('bathymetry-layer', 'visibility');

        // Remove layer and source
        map.removeLayer('bathymetry-layer');
        map.removeSource('bathymetry-source');

        // Re-add source and layer
        map.addSource('bathymetry-source', {
            type: 'raster',
            url: `cog://${CONFIG.BATHY_COG}`,
            tileSize: 256
        });

        map.addLayer({
            id: 'bathymetry-layer',
            type: 'raster',
            source: 'bathymetry-source',
            paint: {
                'raster-opacity': 1.0,
                'raster-resampling': 'nearest'
            },
            layout: {
                visibility: visibility
            }
        }, 'hillshade-layer'); // Insert before hillshade
    }

    map.triggerRepaint();

    // Clear contour cache since depths have changed
    state.contoursCache.clear();
}

/**
 * Handle water level change from slider or checkbox
 */
function onWaterLevelChange() {
    // Update UI elements
    updateWaterLevelDisplay();

    // Refresh bathymetry visualization
    refreshBathymetryTiles();

    // Regenerate contours for current view
    if (state.geoTiffImage && state.layerVisibility.contours) {
        generateContoursForViewport();
    }
}

/**
 * Initialize water level slider controls
 */
function initializeWaterLevelControls() {
    const slider = document.getElementById('water-level-slider');
    const lockCheckbox = document.getElementById('water-level-lock');
    const currentLevelLabel = document.getElementById('current-level-label');

    if (!slider || !lockCheckbox) return;

    // Set initial values
    slider.value = Math.round(CONFIG.CURRENT_STORAGE_GL);
    slider.disabled = state.useCurrentLevel;
    if (currentLevelLabel) {
        currentLevelLabel.textContent = `${CONFIG.CURRENT_STORAGE_GL} GL`;
    }

    // Slider input handler (while dragging)
    slider.addEventListener('input', () => {
        state.customStorageGL = parseFloat(slider.value);
        updateWaterLevelDisplay();
    });

    // Slider change handler (on release) - do the expensive refresh
    slider.addEventListener('change', () => {
        state.customStorageGL = parseFloat(slider.value);
        onWaterLevelChange();
    });

    // Checkbox handler
    lockCheckbox.addEventListener('change', () => {
        state.useCurrentLevel = lockCheckbox.checked;
        slider.disabled = state.useCurrentLevel;

        if (state.useCurrentLevel) {
            // Reset slider to current level
            slider.value = Math.round(CONFIG.CURRENT_STORAGE_GL);
        }

        onWaterLevelChange();
    });
}

// ============================================
// Map Load Handler
// ============================================

map.on('load', async () => {
    try {
        // Initialize water level controls first
        initializeWaterLevelControls();

        // Initialize depth gradient legend
        initializeDepthGradient();

        // Update water level display
        updateWaterLevelDisplay();

        // Add bathymetry layers
        await addBathymetryLayers();

        // Load survey lines
        await loadSurveyLines();

        // Initialize contour generation
        await initializeContourGeneration();

        // Initialize UI handlers
        initializeMeasureTool();
        initializeLayerControls();
        initializeClickHandlers();
        initializeLegendToggles();
        initializeMobileToggle();

        // Hide loading overlay
        document.getElementById('loading').classList.add('hidden');

    } catch (error) {
        console.error('Error loading map:', error);
        document.getElementById('loading-text').textContent = 'Error loading map';
    }
});
