/**
 * Wellington Dam Dive Map
 * Interactive map with bathymetry visualization and survey line overlays
 */

// ============================================
// Configuration
// ============================================

// Volume-to-Level Lookup Table (calibrated from bathymetry + survey cross-reference)
// Generated by generate_volume_lookup.py using:
// - Survey cross-reference: 84.35 GL @ 156.96m AHD
// - Full supply reference: 185 GL @ 165.5m AHD
const VOLUME_TO_LEVEL = [
    { volumeGL: 0, levelAHD: 126.0 },
    { volumeGL: 50, levelAHD: 153.8 },
    { volumeGL: 60, levelAHD: 154.7 },
    { volumeGL: 70, levelAHD: 155.7 },
    { volumeGL: 80, levelAHD: 156.6 },
    { volumeGL: 84.35, levelAHD: 156.96 },
    { volumeGL: 90, levelAHD: 157.5 },
    { volumeGL: 100, levelAHD: 158.3 },
    { volumeGL: 120, levelAHD: 159.9 },
    { volumeGL: 150, levelAHD: 162.6 },
    { volumeGL: 185, levelAHD: 165.5 },
];

/**
 * Get water level from storage volume using calibrated lookup table
 * @param {number} volumeGL - Storage volume in gigalitres
 * @returns {number} Water level in meters AHD
 */
function getWaterLevelFromVolume(volumeGL) {
    if (volumeGL <= VOLUME_TO_LEVEL[0].volumeGL) {
        return VOLUME_TO_LEVEL[0].levelAHD;
    }
    if (volumeGL >= VOLUME_TO_LEVEL[VOLUME_TO_LEVEL.length - 1].volumeGL) {
        return VOLUME_TO_LEVEL[VOLUME_TO_LEVEL.length - 1].levelAHD;
    }

    for (let i = 1; i < VOLUME_TO_LEVEL.length; i++) {
        if (volumeGL <= VOLUME_TO_LEVEL[i].volumeGL) {
            const prev = VOLUME_TO_LEVEL[i - 1];
            const curr = VOLUME_TO_LEVEL[i];
            const t = (volumeGL - prev.volumeGL) / (curr.volumeGL - prev.volumeGL);
            return prev.levelAHD + t * (curr.levelAHD - prev.levelAHD);
        }
    }
    return VOLUME_TO_LEVEL[VOLUME_TO_LEVEL.length - 1].levelAHD;
}

const CONFIG = {
    INITIAL_VIEW: {
        lng: 115.9930,
        lat: -33.3900,
        zoom: 15
    },

    // Bathymetry COG files
    STANDARD_BATHY_COG: 'WellingtonBathy_cog.tif',
    HD_BATHY_COG: 'WellingtonHdBathy_cog.tif',

    // Water level configuration (from calibrated volume model)
    // Update CURRENT_STORAGE_GL to recalculate water level automatically
    CURRENT_STORAGE_GL: 84.35,
    WATER_LEVEL_DATE: '2026-01-26',
    get WATER_LEVEL_AHD() { return getWaterLevelFromVolume(this.CURRENT_STORAGE_GL); },

    // Elevation and depth ranges (dynamically calculated)
    MIN_ELEVATION_AHD: 126.0,
    get MAX_ELEVATION_AHD() { return this.WATER_LEVEL_AHD; },
    get DEPTH_RANGE() { return [0, Math.round(this.WATER_LEVEL_AHD - this.MIN_ELEVATION_AHD)]; },

    // Survey line files and colors
    SURVEY_LINE_FILES: [
        'north_adjusted.csv',
        'south_adjusted.csv',
        'northT1_adjusted.csv',
        'northT2_adjusted.csv',
        'southT1_adjusted.csv'
    ],
    SURVEY_LINE_COLORS: {
        'north_adjusted': '#FF6B6B',
        'south_adjusted': '#4ECDC4',
        'northT1_adjusted': '#FFE66D',
        'northT2_adjusted': '#95E1D3',
        'southT1_adjusted': '#AA96DA'
    },
    SURVEY_LINE_NAMES: {
        'north_adjusted': 'North Line',
        'south_adjusted': 'South Line',
        'northT1_adjusted': 'North Traverse 1',
        'northT2_adjusted': 'North Traverse 2',
        'southT1_adjusted': 'South Traverse 1'
    },

    // Contour configuration
    CONTOUR_COLOR: '#000000',
    CONTOUR_INTERVALS: {
        14: 5,   // Zoom 14-15: 5m intervals
        16: 2    // Zoom 16+: 2m intervals
    },
    // Contours for depth below water surface (negative of AHD minus water level)
    // Generate contours at AHD levels that correspond to 5m, 10m, 15m... depth
    MIN_CONTOUR_DEPTH: 0,
    MAX_CONTOUR_DEPTH: 31
};

// ============================================
// State
// ============================================

const state = {
    layerVisibility: {
        bathymetry: true,
        'hd-bathymetry': true,
        contours: true
    },
    measureMode: false,
    measurePoints: [],
    totalDistance: 0,
    activePopup: null,
    surveyData: {},      // Survey line GeoJSON data by filename
    contoursCache: new Map(),
    isGeneratingContours: false,
    geoTiffImage: null,  // Standard bathymetry reference
    hdGeoTiffImage: null // HD bathymetry reference
};

// ============================================
// Utilities
// ============================================

// Turbo colormap (QGIS-compatible)
const TURBO_COLORMAP = [
    [0.18995, 0.07176, 0.23217], [0.20415, 0.10652, 0.31844],
    [0.22500, 0.16354, 0.45096], [0.24539, 0.23044, 0.59142],
    [0.26280, 0.30639, 0.72968], [0.27701, 0.45152, 0.92347],
    [0.27603, 0.49132, 0.95857], [0.26592, 0.55979, 0.99583],
    [0.25425, 0.58950, 0.99896], [0.23874, 0.61931, 0.99485],
    [0.21382, 0.65886, 0.97959], [0.18625, 0.69775, 0.95498],
    [0.15173, 0.74472, 0.91416], [0.12151, 0.78896, 0.86581],
    [0.10026, 0.82955, 0.81389], [0.09320, 0.87211, 0.75237],
    [0.10815, 0.90142, 0.70599], [0.14391, 0.92680, 0.65448],
    [0.18491, 0.94484, 0.60713], [0.22877, 0.95304, 0.58199],
    [0.27597, 0.97092, 0.51653], [0.32006, 0.97974, 0.47654],
    [0.36581, 0.98702, 0.43688], [0.41229, 0.99268, 0.39826],
    [0.45854, 0.99663, 0.36140], [0.50362, 0.99879, 0.32701],
    [0.54658, 0.99907, 0.29581], [0.59891, 0.99638, 0.26038],
    [0.65394, 0.98775, 0.22835], [0.71577, 0.96875, 0.20815],
    [0.78563, 0.93579, 0.20336], [0.47960, 0.01583, 0.01055]
];

/**
 * Map depth value to RGB color using Turbo colormap
 * Shallow (0m) = blue end, Deep (30m) = red end
 */
function getTurboColorForDepth(depth, minDepth = 0, maxDepth = 31) {
    // Normalize depth to 0-1 range
    const normalized = (depth - minDepth) / (maxDepth - minDepth);
    const clamped = Math.max(0, Math.min(1, normalized));

    // Map to colormap index
    const index = clamped * (TURBO_COLORMAP.length - 1);
    const lower = Math.floor(index);
    const upper = Math.ceil(index);
    const fraction = index - lower;

    // Interpolate between colors
    const colorLower = TURBO_COLORMAP[lower];
    const colorUpper = TURBO_COLORMAP[upper];

    return [
        Math.round((colorLower[0] + (colorUpper[0] - colorLower[0]) * fraction) * 255),
        Math.round((colorLower[1] + (colorUpper[1] - colorLower[1]) * fraction) * 255),
        Math.round((colorLower[2] + (colorUpper[2] - colorLower[2]) * fraction) * 255)
    ];
}

/**
 * Convert bed elevation (AHD) to depth below water surface
 */
function elevationToDepth(elevationAHD) {
    return CONFIG.WATER_LEVEL_AHD - elevationAHD;
}

/**
 * Calculate distance between two points using Haversine formula
 */
function haversineDistance([lon1, lat1], [lon2, lat2]) {
    const R = 6371000; // Earth radius in meters
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;
    const a = Math.sin(dLat / 2) ** 2 +
        Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
        Math.sin(dLon / 2) ** 2;
    return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

/**
 * Format distance for display
 */
function formatDistance(meters) {
    if (meters >= 1000) {
        return `${(meters / 1000).toFixed(2)} km`;
    }
    return `${meters.toFixed(1)} m`;
}

/**
 * Format coordinates in multiple formats
 */
function formatCoordinates(lng, lat) {
    const gmaps = `${lat.toFixed(6)}, ${lng.toFixed(6)}`;
    const latDeg = Math.floor(Math.abs(lat));
    const latMin = ((Math.abs(lat) % 1) * 60).toFixed(3);
    const latDir = lat >= 0 ? 'N' : 'S';
    const lngDeg = Math.floor(Math.abs(lng));
    const lngMin = ((Math.abs(lng) % 1) * 60).toFixed(3);
    const lngDir = lng >= 0 ? 'E' : 'W';
    const dm = `${latDeg}° ${latMin}' ${latDir}, ${lngDeg}° ${lngMin}' ${lngDir}`;
    return { gmaps, display: dm };
}

/**
 * Debounce helper function
 */
function debounce(func, wait) {
    let timeout;
    return function executedFunction(...args) {
        const later = () => {
            clearTimeout(timeout);
            func(...args);
        };
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
    };
}

// ============================================
// Map Initialization
// ============================================

// Register COG protocol for bathymetry raster
maplibregl.addProtocol('cog', MaplibreCOGProtocol.cogProtocol);

const map = new maplibregl.Map({
    container: 'map',
    style: {
        version: 8,
        glyphs: 'https://demotiles.maplibre.org/font/{fontstack}/{range}.pbf',
        sources: {
            'esri-satellite': {
                type: 'raster',
                tiles: [
                    'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'
                ],
                tileSize: 256,
                maxzoom: 18
            }
        },
        layers: [
            {
                id: 'satellite-layer',
                type: 'raster',
                source: 'esri-satellite',
                minzoom: 0
            }
        ]
    },
    center: [CONFIG.INITIAL_VIEW.lng, CONFIG.INITIAL_VIEW.lat],
    zoom: CONFIG.INITIAL_VIEW.zoom,
    minZoom: 12,
    maxZoom: 20,
    maxPitch: 0,
    dragRotate: false,
    attributionControl: false
});

// Add attribution control (compact)
map.addControl(new maplibregl.AttributionControl({ compact: true }), 'bottom-right');

// Add navigation control
map.addControl(new maplibregl.NavigationControl({ showCompass: false }), 'bottom-right');

// ============================================
// Depth Gradient Legend
// ============================================

function initializeDepthGradient() {
    const gradientEl = document.getElementById('depth-gradient');
    if (!gradientEl) return;

    // Generate CSS gradient from Turbo colormap
    const stops = [];
    for (let i = 0; i <= 10; i++) {
        const depth = (i / 10) * CONFIG.DEPTH_RANGE[1];
        const [r, g, b] = getTurboColorForDepth(depth, CONFIG.DEPTH_RANGE[0], CONFIG.DEPTH_RANGE[1]);
        stops.push(`rgb(${r}, ${g}, ${b}) ${i * 10}%`);
    }

    gradientEl.style.background = `linear-gradient(to bottom, ${stops.join(', ')})`;
}

// ============================================
// Bathymetry Layers
// ============================================

async function addBathymetryLayers() {
    const waterLevel = CONFIG.WATER_LEVEL_AHD;
    const minDepth = CONFIG.DEPTH_RANGE[0];
    const maxDepth = CONFIG.DEPTH_RANGE[1];

    // Color function for standard bathymetry
    MaplibreCOGProtocol.setColorFunction(CONFIG.STANDARD_BATHY_COG, (pixel, color, metadata) => {
        const elevation = pixel[0];

        // Handle NoData values
        if (elevation === metadata.noData || elevation >= 1e5 || !Number.isFinite(elevation)) {
            color.set([0, 0, 0, 0]);
            return;
        }

        // Don't render areas above water level (not submerged)
        if (elevation > waterLevel) {
            color.set([0, 0, 0, 0]);
            return;
        }

        // Calculate depth and get color
        const depth = waterLevel - elevation;
        const [r, g, b] = getTurboColorForDepth(depth, minDepth, maxDepth);
        color.set([r, g, b, 255]);
    });

    // Color function for HD bathymetry (same as standard)
    MaplibreCOGProtocol.setColorFunction(CONFIG.HD_BATHY_COG, (pixel, color, metadata) => {
        const elevation = pixel[0];

        if (elevation === metadata.noData || elevation >= 1e5 || !Number.isFinite(elevation)) {
            color.set([0, 0, 0, 0]);
            return;
        }

        if (elevation > waterLevel) {
            color.set([0, 0, 0, 0]);
            return;
        }

        const depth = waterLevel - elevation;
        const [r, g, b] = getTurboColorForDepth(depth, minDepth, maxDepth);
        color.set([r, g, b, 255]);
    });

    try {
        // Add standard bathymetry source and layers
        map.addSource('bathymetry-source', {
            type: 'raster',
            url: `cog://${CONFIG.STANDARD_BATHY_COG}`,
            tileSize: 256
        });

        map.addSource('hillshade-source', {
            type: 'raster-dem',
            url: `cog://${CONFIG.STANDARD_BATHY_COG}`,
            tileSize: 256
        });

        map.addLayer({
            id: 'bathymetry-layer',
            type: 'raster',
            source: 'bathymetry-source',
            paint: {
                'raster-opacity': 1.0,  // Full opacity per plan
                'raster-resampling': 'nearest'
            },
            layout: {
                visibility: state.layerVisibility.bathymetry ? 'visible' : 'none'
            }
        });

        map.addLayer({
            id: 'hillshade-layer',
            type: 'hillshade',
            source: 'hillshade-source',
            paint: {
                'hillshade-illumination-direction': 45,
                'hillshade-shadow-color': '#000000',
                'hillshade-highlight-color': '#FFFFFF',
                'hillshade-accent-color': '#000000',
                'hillshade-exaggeration': 0.05
            },
            layout: {
                visibility: state.layerVisibility.bathymetry ? 'visible' : 'none'
            }
        }, 'bathymetry-layer');

        // Add HD bathymetry source and layer (renders on top where it exists)
        map.addSource('hd-bathymetry-source', {
            type: 'raster',
            url: `cog://${CONFIG.HD_BATHY_COG}`,
            tileSize: 256
        });

        map.addLayer({
            id: 'hd-bathymetry-layer',
            type: 'raster',
            source: 'hd-bathymetry-source',
            paint: {
                'raster-opacity': 1.0,
                'raster-resampling': 'nearest'
            },
            layout: {
                visibility: state.layerVisibility['hd-bathymetry'] ? 'visible' : 'none'
            }
        });

        console.log('Bathymetry layers added successfully');
    } catch (error) {
        console.error('Failed to add bathymetry layers:', error);
    }
}

// ============================================
// Survey Line Loading
// ============================================

async function loadSurveyLines() {
    const allFeatures = [];

    for (const filename of CONFIG.SURVEY_LINE_FILES) {
        try {
            const response = await fetch(filename);
            if (!response.ok) {
                console.warn(`Could not load ${filename}`);
                continue;
            }

            const csvText = await response.text();
            const lines = csvText.trim().split('\n');
            const headers = lines[0].split(',');

            // Find column indices
            const yIndex = headers.findIndex(h => h.trim() === 'Y');
            const xIndex = headers.findIndex(h => h.trim() === 'X');
            const elevIndex = headers.findIndex(h => h.trim() === 'Elevation');
            const markerIndex = headers.findIndex(h => h.trim() === 'Marker');

            if (yIndex === -1 || xIndex === -1) {
                console.warn(`Missing Y/X columns in ${filename}`);
                continue;
            }

            // Parse coordinates and create line
            const coordinates = [];
            const points = [];

            for (let i = 1; i < lines.length; i++) {
                const values = lines[i].split(',');
                const lat = parseFloat(values[yIndex]);
                const lng = parseFloat(values[xIndex]);
                const elevation = elevIndex !== -1 ? parseFloat(values[elevIndex]) : null;
                const marker = markerIndex !== -1 ? values[markerIndex]?.trim() : null;

                if (!isNaN(lat) && !isNaN(lng)) {
                    coordinates.push([lng, lat]);
                    points.push({
                        coord: [lng, lat],
                        elevation: elevation,  // Depth below surface (negative)
                        marker: marker
                    });
                }
            }

            if (coordinates.length >= 2) {
                // Store the survey data
                const lineKey = filename.replace('.csv', '');
                state.surveyData[lineKey] = {
                    coordinates,
                    points,
                    color: CONFIG.SURVEY_LINE_COLORS[lineKey],
                    name: CONFIG.SURVEY_LINE_NAMES[lineKey]
                };

                // Create LineString feature
                allFeatures.push({
                    type: 'Feature',
                    geometry: {
                        type: 'LineString',
                        coordinates: coordinates
                    },
                    properties: {
                        lineKey: lineKey,
                        name: CONFIG.SURVEY_LINE_NAMES[lineKey],
                        color: CONFIG.SURVEY_LINE_COLORS[lineKey],
                        pointCount: coordinates.length
                    }
                });

                console.log(`Loaded ${filename}: ${coordinates.length} points`);
            }
        } catch (error) {
            console.error(`Error loading ${filename}:`, error);
        }
    }

    // Add survey lines to map
    if (allFeatures.length > 0) {
        map.addSource('survey-lines', {
            type: 'geojson',
            data: {
                type: 'FeatureCollection',
                features: allFeatures
            }
        });

        // Build color expression
        const colorExpression = ['match', ['get', 'lineKey']];
        Object.entries(CONFIG.SURVEY_LINE_COLORS).forEach(([key, color]) => {
            colorExpression.push(key, color);
        });
        colorExpression.push('#888888');

        // Add visible line layer
        map.addLayer({
            id: 'survey-lines-layer',
            type: 'line',
            source: 'survey-lines',
            paint: {
                'line-color': colorExpression,
                'line-width': 4,
                'line-opacity': 0.9
            }
        });

        // Add hit area for easier clicking
        map.addLayer({
            id: 'survey-lines-hitarea',
            type: 'line',
            source: 'survey-lines',
            paint: {
                'line-color': '#000000',
                'line-width': 20,
                'line-opacity': 0
            }
        });
    }
}

// ============================================
// Contour Generation
// ============================================

async function initializeContourGeneration() {
    try {
        const tiff = await GeoTIFF.fromUrl(CONFIG.STANDARD_BATHY_COG, {
            allowFullFile: false,
            cacheSize: 100
        });

        state.geoTiffImage = await tiff.getImage();

        // Add empty contours source
        map.addSource('contours-source', {
            type: 'geojson',
            data: { type: 'FeatureCollection', features: [] }
        });

        // Add contour line layer
        map.addLayer({
            id: 'contours-layer',
            type: 'line',
            source: 'contours-source',
            paint: {
                'line-color': CONFIG.CONTOUR_COLOR,
                'line-width': [
                    'case',
                    ['==', ['%', ['get', 'depth'], 10], 0],
                    2,
                    1
                ],
                'line-opacity': 0.6
            },
            layout: {
                visibility: state.layerVisibility.contours ? 'visible' : 'none'
            },
            minzoom: Math.min(...Object.keys(CONFIG.CONTOUR_INTERVALS).map(Number))
        }, 'survey-lines-layer');

        // Add contour labels
        map.addLayer({
            id: 'contours-labels',
            type: 'symbol',
            source: 'contours-source',
            paint: {
                'text-color': CONFIG.CONTOUR_COLOR,
                'text-halo-color': '#ffffff',
                'text-halo-width': 2,
                'text-opacity': 0.9
            },
            layout: {
                'text-field': ['concat', ['get', 'depth'], 'm'],
                'text-font': ['Open Sans Regular', 'Arial Unicode MS Regular'],
                'text-size': 11,
                'symbol-placement': 'line',
                'symbol-spacing': 200,
                'text-rotation-alignment': 'map',
                'text-pitch-alignment': 'viewport',
                'text-max-angle': 30,
                'text-padding': 10,
                visibility: state.layerVisibility.contours ? 'visible' : 'none'
            },
            minzoom: Math.min(...Object.keys(CONFIG.CONTOUR_INTERVALS).map(Number))
        }, 'survey-lines-layer');

        // Generate initial contours
        if (map.getZoom() >= Math.min(...Object.keys(CONFIG.CONTOUR_INTERVALS).map(Number))) {
            await generateContoursForViewport();
        }

        // Regenerate on map movement
        map.on('moveend', debounce(generateContoursForViewport, 300));

    } catch (error) {
        console.error('Failed to initialize contour generation:', error);
    }
}

async function generateContoursForViewport() {
    if (state.isGeneratingContours || !state.geoTiffImage) return;
    if (!state.layerVisibility.contours) return;

    const zoom = Math.floor(map.getZoom());
    const minContourZoom = Math.min(...Object.keys(CONFIG.CONTOUR_INTERVALS).map(Number));
    if (zoom < minContourZoom) return;

    const bounds = map.getBounds();

    // Determine contour interval
    let interval = 10;
    for (const [zoomThreshold, int] of Object.entries(CONFIG.CONTOUR_INTERVALS).sort((a, b) => b[0] - a[0])) {
        if (zoom >= parseInt(zoomThreshold)) {
            interval = int;
            break;
        }
    }

    // Check cache
    const cacheKey = `${zoom}-${interval}-${bounds.toString()}`;
    if (state.contoursCache.has(cacheKey)) {
        map.getSource('contours-source').setData(state.contoursCache.get(cacheKey));
        return;
    }

    state.isGeneratingContours = true;
    document.getElementById('contours-loading')?.classList.add('active');

    try {
        const imageBbox = state.geoTiffImage.getBoundingBox();
        const imageWidth = state.geoTiffImage.getWidth();
        const imageHeight = state.geoTiffImage.getHeight();

        // WGS84 to Web Mercator
        const lngLatToWebMercator = (lng, lat) => {
            const x = (lng * 20037508.34) / 180;
            let y = Math.log(Math.tan(((90 + lat) * Math.PI) / 360)) / (Math.PI / 180);
            y = (y * 20037508.34) / 180;
            return [x, y];
        };

        const [minX, minY] = lngLatToWebMercator(bounds.getWest(), bounds.getSouth());
        const [maxX, maxY] = lngLatToWebMercator(bounds.getEast(), bounds.getNorth());

        const bufferX = (maxX - minX) * 0.5;
        const bufferY = (maxY - minY) * 0.5;

        // Calculate pixel window
        const left = Math.floor(((minX - bufferX - imageBbox[0]) / (imageBbox[2] - imageBbox[0])) * imageWidth);
        const right = Math.ceil(((maxX + bufferX - imageBbox[0]) / (imageBbox[2] - imageBbox[0])) * imageWidth);
        const top = Math.floor(((imageBbox[3] - (maxY + bufferY)) / (imageBbox[3] - imageBbox[1])) * imageHeight);
        const bottom = Math.ceil(((imageBbox[3] - (minY - bufferY)) / (imageBbox[3] - imageBbox[1])) * imageHeight);

        const windowLeft = Math.max(0, left);
        const windowTop = Math.max(0, top);
        const windowRight = Math.min(imageWidth, right);
        const windowBottom = Math.min(imageHeight, bottom);
        const windowWidth = windowRight - windowLeft;
        const windowHeight = windowBottom - windowTop;

        // Determine resolution
        const isMobile = globalThis.innerWidth <= 768;
        const baseResolution = isMobile ? 256 : 512;
        const targetPixels = Math.min(
            baseResolution * Math.pow(2, Math.max(0, zoom - 15)),
            isMobile ? 1024 : 2048
        );

        const aspectRatio = windowWidth / windowHeight;
        let width, height;
        if (aspectRatio > 1) {
            width = targetPixels;
            height = Math.floor(targetPixels / aspectRatio);
        } else {
            height = targetPixels;
            width = Math.floor(targetPixels * aspectRatio);
        }

        // Read elevation data
        const data = await state.geoTiffImage.readRasters({
            window: [windowLeft, windowTop, windowRight, windowBottom],
            width,
            height,
            fillValue: -9999,
            resampleMethod: 'linear'
        });

        const elevationGrid = data[0];

        // Calculate actual extent in Web Mercator
        const actualMinX = imageBbox[0] + (windowLeft / imageWidth) * (imageBbox[2] - imageBbox[0]);
        const actualMaxX = imageBbox[0] + (windowRight / imageWidth) * (imageBbox[2] - imageBbox[0]);
        const actualMaxY = imageBbox[3] - (windowTop / imageHeight) * (imageBbox[3] - imageBbox[1]);
        const actualMinY = imageBbox[3] - (windowBottom / imageHeight) * (imageBbox[3] - imageBbox[1]);

        // Generate depth contour thresholds (converted to AHD elevations)
        // Contours at depths: 5m, 10m, 15m, 20m, 25m, 30m
        // AHD = water_level - depth
        const thresholds = [];
        for (let depth = interval; depth <= CONFIG.MAX_CONTOUR_DEPTH; depth += interval) {
            const ahdLevel = CONFIG.WATER_LEVEL_AHD - depth;
            if (ahdLevel >= CONFIG.MIN_ELEVATION_AHD) {
                thresholds.push(ahdLevel);
            }
        }

        // Generate contours
        const contourGenerator = d3.contours()
            .size([width, height])
            .thresholds(thresholds)
            .smooth(true);

        const contourMultiPolygons = contourGenerator(elevationGrid);

        // Web Mercator to WGS84
        const webMercatorToLngLat = (x, y) => {
            const lng = (x / 20037508.34) * 180;
            let lat = (y / 20037508.34) * 180;
            lat = (180 / Math.PI) * (2 * Math.atan(Math.exp((lat * Math.PI) / 180)) - Math.PI / 2);
            return [lng, lat];
        };

        // Convert to GeoJSON features
        const features = [];
        const viewportMinX = lngLatToWebMercator(bounds.getWest(), bounds.getSouth())[0];
        const viewportMaxX = lngLatToWebMercator(bounds.getEast(), bounds.getNorth())[0];
        const viewportMinY = lngLatToWebMercator(bounds.getWest(), bounds.getSouth())[1];
        const viewportMaxY = lngLatToWebMercator(bounds.getEast(), bounds.getNorth())[1];

        for (const multiPolygon of contourMultiPolygons) {
            if (multiPolygon.coordinates.length === 0) continue;

            const ahdLevel = multiPolygon.value;
            const depth = Math.round(CONFIG.WATER_LEVEL_AHD - ahdLevel);

            for (const polygon of multiPolygon.coordinates) {
                for (const ring of polygon) {
                    // Check for NoData adjacency
                    let nearNoData = false;
                    const samplePoints = Math.min(ring.length, 20);
                    const step = Math.max(1, Math.floor(ring.length / samplePoints));

                    for (let i = 0; i < ring.length; i += step) {
                        const [x, y] = ring[i];
                        const px = Math.floor(x);
                        const py = Math.floor(y);

                        for (let dy = -1; dy <= 1; dy++) {
                            for (let dx = -1; dx <= 1; dx++) {
                                const checkX = px + dx;
                                const checkY = py + dy;
                                if (checkX >= 0 && checkX < width && checkY >= 0 && checkY < height) {
                                    const idx = checkY * width + checkX;
                                    const value = elevationGrid[idx];
                                    if (value === -9999 || value >= 1e5) {
                                        nearNoData = true;
                                        break;
                                    }
                                }
                            }
                            if (nearNoData) break;
                        }
                        if (nearNoData) break;
                    }

                    if (nearNoData) continue;

                    // Transform to geographic coordinates
                    const geoCoords = ring.map(([x, y]) => {
                        const mercatorX = actualMinX + (x / width) * (actualMaxX - actualMinX);
                        const mercatorY = actualMaxY - (y / height) * (actualMaxY - actualMinY);
                        return webMercatorToLngLat(mercatorX, mercatorY);
                    });

                    // Filter edge contours
                    const margin = (viewportMaxX - viewportMinX) * 0.01;
                    let hasInteriorPoint = false;

                    for (const [lng, lat] of geoCoords) {
                        const [mx, my] = lngLatToWebMercator(lng, lat);
                        if (mx > viewportMinX + margin && mx < viewportMaxX - margin &&
                            my > viewportMinY + margin && my < viewportMaxY - margin) {
                            hasInteriorPoint = true;
                            break;
                        }
                    }

                    if (!hasInteriorPoint) continue;

                    features.push({
                        type: 'Feature',
                        properties: {
                            depth: depth,
                            ahdLevel: ahdLevel,
                            interval
                        },
                        geometry: {
                            type: 'LineString',
                            coordinates: geoCoords
                        }
                    });
                }
            }
        }

        const geojson = {
            type: 'FeatureCollection',
            features
        };

        if (map.getSource('contours-source')) {
            map.getSource('contours-source').setData(geojson);
        }

        // Cache
        if (state.contoursCache.size > 20) {
            const firstKey = state.contoursCache.keys().next().value;
            state.contoursCache.delete(firstKey);
        }
        state.contoursCache.set(cacheKey, geojson);

    } catch (error) {
        console.error('Failed to generate contours:', error);
    } finally {
        state.isGeneratingContours = false;
        document.getElementById('contours-loading')?.classList.remove('active');
    }
}

// ============================================
// Measure Tool
// ============================================

function initializeMeasureTool() {
    const measureBtn = document.getElementById('measure-btn');
    const clearBtn = document.getElementById('clear-btn');

    measureBtn.addEventListener('click', (e) => {
        e.stopPropagation();
        state.measureMode = !state.measureMode;
        measureBtn.classList.toggle('active', state.measureMode);

        if (state.measureMode) {
            document.body.classList.add('measure-mode-active');
            clearBtn.style.display = 'block';
        } else {
            document.body.classList.remove('measure-mode-active');
        }

        measureBtn.blur();
    });

    clearBtn.addEventListener('click', (e) => {
        e.stopPropagation();
        clearMeasurements();
    });

    // Add measure sources
    map.addSource('measure-line', {
        type: 'geojson',
        data: { type: 'FeatureCollection', features: [] }
    });

    map.addSource('measure-points', {
        type: 'geojson',
        data: { type: 'FeatureCollection', features: [] }
    });

    map.addLayer({
        id: 'measure-line-layer',
        type: 'line',
        source: 'measure-line',
        paint: {
            'line-color': '#0891b2',
            'line-width': 3,
            'line-dasharray': [2, 2]
        }
    });

    map.addLayer({
        id: 'measure-points-layer',
        type: 'circle',
        source: 'measure-points',
        paint: {
            'circle-radius': 6,
            'circle-color': '#0891b2',
            'circle-stroke-color': '#ffffff',
            'circle-stroke-width': 2
        }
    });
}

function clearMeasurements() {
    state.measurePoints = [];
    state.totalDistance = 0;

    document.getElementById('measure-panel').style.display = 'none';
    document.getElementById('measure-total').textContent = '0 m';
    document.getElementById('measure-items').innerHTML = '';

    map.getSource('measure-line').setData({ type: 'FeatureCollection', features: [] });
    map.getSource('measure-points').setData({ type: 'FeatureCollection', features: [] });
}

async function addMeasurePoint(lngLat) {
    const measurePanel = document.getElementById('measure-panel');
    const measureTotal = document.getElementById('measure-total');
    const measureItems = document.getElementById('measure-items');

    let distance = 0;
    let displayName = 'Start point';

    if (state.measurePoints.length > 0) {
        const lastPoint = state.measurePoints[state.measurePoints.length - 1];
        distance = haversineDistance(
            [lastPoint.lng, lastPoint.lat],
            [lngLat.lng, lngLat.lat]
        );
        displayName = `Point ${state.measurePoints.length + 1}`;
    }

    state.measurePoints.push({
        lng: lngLat.lng,
        lat: lngLat.lat,
        distance: distance
    });

    state.totalDistance += distance;

    measurePanel.style.display = 'block';
    measureTotal.textContent = formatDistance(state.totalDistance);

    const itemEl = document.createElement('div');
    itemEl.className = 'measure-item';
    itemEl.innerHTML = `
        <span class="measure-item-name">
            <span class="measure-item-dot" style="background: #0891b2;"></span>
            ${displayName}
        </span>
        <span class="measure-item-info">
            <span class="measure-item-distance">${formatDistance(distance)}</span>
        </span>
    `;
    measureItems.appendChild(itemEl);

    updateMeasureVisualization();
}

function updateMeasureVisualization() {
    const pointFeatures = state.measurePoints.map((point, index) => ({
        type: 'Feature',
        geometry: {
            type: 'Point',
            coordinates: [point.lng, point.lat]
        },
        properties: { index }
    }));

    map.getSource('measure-points').setData({
        type: 'FeatureCollection',
        features: pointFeatures
    });

    if (state.measurePoints.length >= 2) {
        const lineCoords = state.measurePoints.map(p => [p.lng, p.lat]);
        map.getSource('measure-line').setData({
            type: 'FeatureCollection',
            features: [{
                type: 'Feature',
                geometry: {
                    type: 'LineString',
                    coordinates: lineCoords
                },
                properties: {}
            }]
        });
    }
}

// ============================================
// Click Handlers
// ============================================

function initializeClickHandlers() {
    // Survey line click handler
    map.on('click', 'survey-lines-hitarea', (e) => {
        if (e.features.length === 0) return;

        const feature = e.features[0];
        const props = feature.properties;

        if (state.measureMode) {
            addMeasurePoint(e.lngLat);
        } else {
            const content = `
                <div class="segment-popup">
                    <div class="popup-title">${props.name}</div>
                    <div class="popup-row">
                        <span class="popup-label">Points</span>
                        ${props.pointCount}
                    </div>
                </div>
            `;

            if (state.activePopup) state.activePopup.remove();
            state.activePopup = new maplibregl.Popup({ closeButton: true, maxWidth: '280px' })
                .setLngLat(e.lngLat)
                .setHTML(content)
                .addTo(map);
        }
    });

    // General map click
    map.on('click', (e) => {
        if (!state.measureMode) return;

        const features = map.queryRenderedFeatures(e.point, {
            layers: ['survey-lines-hitarea']
        });

        if (features.length === 0) {
            addMeasurePoint(e.lngLat);
        }
    });

    // Cursor changes
    map.on('mouseenter', 'survey-lines-hitarea', () => {
        if (!state.measureMode) {
            map.getCanvas().style.cursor = 'pointer';
        }
    });

    map.on('mouseleave', 'survey-lines-hitarea', () => {
        if (!state.measureMode) {
            map.getCanvas().style.cursor = '';
        }
    });
}

// ============================================
// Layer Controls
// ============================================

function initializeLayerControls() {
    const layerControls = document.querySelectorAll('.layer-control[data-layer]');

    layerControls.forEach(control => {
        const layerId = control.dataset.layer;
        const checkbox = control.querySelector('input[type="checkbox"]');

        checkbox.addEventListener('change', () => {
            state.layerVisibility[layerId] = checkbox.checked;
            const visibility = checkbox.checked ? 'visible' : 'none';

            if (layerId === 'bathymetry') {
                if (map.getLayer('bathymetry-layer')) {
                    map.setLayoutProperty('bathymetry-layer', 'visibility', visibility);
                }
                if (map.getLayer('hillshade-layer')) {
                    map.setLayoutProperty('hillshade-layer', 'visibility', visibility);
                }
            } else if (layerId === 'hd-bathymetry') {
                if (map.getLayer('hd-bathymetry-layer')) {
                    map.setLayoutProperty('hd-bathymetry-layer', 'visibility', visibility);
                }
            } else if (layerId === 'contours') {
                if (map.getLayer('contours-layer')) {
                    map.setLayoutProperty('contours-layer', 'visibility', visibility);
                }
                if (map.getLayer('contours-labels')) {
                    map.setLayoutProperty('contours-labels', 'visibility', visibility);
                }
                if (checkbox.checked) {
                    generateContoursForViewport();
                }
            }
        });
    });
}

// ============================================
// Mobile Toggle
// ============================================

function initializeMobileToggle() {
    const titleCard = document.querySelector('.title-card');
    const legend = document.querySelector('.legend');
    const legendToggle = document.getElementById('legend-toggle');

    titleCard.addEventListener('click', (e) => {
        if (globalThis.innerWidth <= 768) {
            if (e.target.tagName !== 'A') {
                titleCard.classList.toggle('expanded');
            }
        }
    });

    if (legendToggle && legend) {
        legendToggle.addEventListener('click', (e) => {
            e.stopPropagation();
            e.preventDefault();
            legend.classList.toggle('collapsed');

            const isCollapsed = legend.classList.contains('collapsed');
            localStorage.setItem('legendCollapsed', isCollapsed ? 'true' : 'false');
        });

        if (globalThis.innerWidth <= 768) {
            const savedState = localStorage.getItem('legendCollapsed');
            if (savedState === 'true') {
                legend.classList.add('collapsed');
            }
        }
    }
}

// ============================================
// Legend Zoom to Survey Line
// ============================================

function initializeLegendToggles() {
    const colorItems = document.querySelectorAll('.color-item[data-line]');

    colorItems.forEach(item => {
        item.addEventListener('click', () => {
            const lineKey = item.dataset.line;
            const surveyLine = state.surveyData[lineKey];

            if (surveyLine && surveyLine.coordinates.length > 0) {
                const lngs = surveyLine.coordinates.map(c => c[0]);
                const lats = surveyLine.coordinates.map(c => c[1]);

                const bounds = [
                    [Math.min(...lngs), Math.min(...lats)],
                    [Math.max(...lngs), Math.max(...lats)]
                ];

                const isMobile = globalThis.innerWidth <= 768;
                const padding = isMobile
                    ? { top: 120, bottom: 250, left: 50, right: 50 }
                    : { top: 100, bottom: 100, left: 400, right: 100 };

                map.fitBounds(bounds, {
                    padding: padding,
                    maxZoom: 17,
                    duration: 1000
                });

                colorItems.forEach(ci => ci.classList.remove('selected'));
                item.classList.add('selected');
            }
        });
    });
}

// ============================================
// Context Menu
// ============================================

map.on('contextmenu', (e) => {
    const existing = document.getElementById('context-menu');
    if (existing) existing.remove();

    const { lng, lat } = e.lngLat;
    const coords = formatCoordinates(lng, lat);

    const menu = document.createElement('div');
    menu.id = 'context-menu';
    menu.className = 'context-menu';
    menu.style.left = `${e.point.x}px`;
    menu.style.top = `${e.point.y}px`;

    menu.innerHTML = `
        <div class="context-menu-item" id="copy-dd">
            <span>Copy Decimal Degrees</span>
            <span style="opacity: 0.5; margin-left: 12px; font-size: 0.7rem;">${coords.gmaps}</span>
        </div>
        <div class="context-menu-separator"></div>
        <div class="context-menu-item" id="copy-dm">
            <span>Copy Decimal Minutes</span>
            <span style="opacity: 0.5; margin-left: 12px; font-size: 0.7rem;">${coords.display}</span>
        </div>
        <div class="context-menu-separator"></div>
        <div class="context-menu-item" id="copy-link">
            <span>Copy Link</span>
        </div>
    `;

    document.body.appendChild(menu);

    document.getElementById('copy-dd').addEventListener('click', () => {
        navigator.clipboard.writeText(coords.gmaps);
        menu.remove();
    });

    document.getElementById('copy-dm').addEventListener('click', () => {
        navigator.clipboard.writeText(coords.display);
        menu.remove();
    });

    document.getElementById('copy-link').addEventListener('click', () => {
        const url = `${globalThis.location.origin}${globalThis.location.pathname}#${lat.toFixed(6)},${lng.toFixed(6)}`;
        navigator.clipboard.writeText(url);
        menu.remove();
    });

    const closeMenu = () => {
        menu.remove();
        document.removeEventListener('click', closeMenu);
    };
    setTimeout(() => document.addEventListener('click', closeMenu), 100);
});

// ============================================
// Water Level Display
// ============================================

function updateWaterLevelNote() {
    const noteEl = document.getElementById('water-level-note');
    if (!noteEl) return;

    const level = CONFIG.WATER_LEVEL_AHD.toFixed(1);
    const storage = CONFIG.CURRENT_STORAGE_GL;
    const date = CONFIG.WATER_LEVEL_DATE;

    noteEl.textContent = `Water level: ~${level}m AHD (${storage} GL)`;
    noteEl.title = `Calculated from Water Corporation storage data (${date})`;

    // Update depth labels based on calculated range
    const depthLabelsEl = document.querySelector('.depth-labels');
    if (depthLabelsEl) {
        const maxDepth = CONFIG.DEPTH_RANGE[1];
        const midDepth = Math.round(maxDepth / 2);
        depthLabelsEl.innerHTML = `<span>0m</span><span>${midDepth}m</span><span>${maxDepth}m</span>`;
    }
}

// ============================================
// Map Load Handler
// ============================================

map.on('load', async () => {
    try {
        // Initialize depth gradient legend
        initializeDepthGradient();

        // Update water level display
        updateWaterLevelNote();

        // Add bathymetry layers
        await addBathymetryLayers();

        // Load survey lines
        await loadSurveyLines();

        // Initialize contour generation
        await initializeContourGeneration();

        // Initialize UI handlers
        initializeMeasureTool();
        initializeLayerControls();
        initializeClickHandlers();
        initializeLegendToggles();
        initializeMobileToggle();

        // Hide loading overlay
        document.getElementById('loading').classList.add('hidden');

    } catch (error) {
        console.error('Error loading map:', error);
        document.getElementById('loading-text').textContent = 'Error loading map';
    }
});
